### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by EWouters** [ukdtom/WebTools.bundle#287] opened 2017-04-05 10:58 UTC
Hi,

I really like this project and have it installed on my server. I would like to host in on my server at example.com/plexwebtools

Would it be possible to add a reverse proxy feature? Possibly stored in WebTools.bundle/Contents/DefaultPrefs.json

**Comment by ukdtom** [comment] 2017-04-05 11:27
Duplicate of #123

**Closed by ukdtom** 2017-04-05 11:27 UTC

**Comment by EWouters** [comment] 2017-04-10 22:04
Thanks for implementing this! (85c5003)
