### ISSUE TITLE
Subtitles: 'Load More' doesn't do anything when 'hide movies without subtitles' activated

### ISSUE THREAD

**Issue by OttoKerner** [ukdtom/WebTools.bundle#439] opened 2017-11-30 20:45 UTC
## Environment
- **PMS Platform(s) OS**: Win
- **PMS Version**: 1.10.1.4534
- **Name of Browser**: Firefox

## Error shown
When 'hide movies without subtitles' is activated, one cannot load more movies into the screen.
![load_more](https://user-images.githubusercontent.com/10280992/33454019-c98e2a56-d617-11e7-86d9-46449444f817.png)

**Comment by ukdtom** [comment] 2017-11-30 21:57
@OttoKerner Check out the tommy-work branch

**Comment by OttoKerner** [comment] 2017-11-30 22:27
Working now.

**Comment by OttoKerner** [comment] 2017-11-30 22:31
I closed this too early.
It appears, that 'Load more' still loads a chunk of movies, regardless if they have subtitles or not.
if you only have a few movies with subs, it could appear as if 'Load more' won't do anything.

I think, counting how many movies to load needs to be done after the filtering for subtitles.

**Comment by ukdtom** [comment] 2017-11-30 22:38
Just updated the Tommy Work branch, and do seem to work for me now, so if you could reapply?

**Comment by creoludifico** [comment] 2017-11-30 22:45
Could the problem be that the items are being appended further up in the list because of sorting and therefore not as "visible" as it should be? 😄

**Comment by ukdtom** [comment] 2017-11-30 22:48
Heh, that might be an issue....

@creoludifico ?

**Comment by creoludifico** [comment] 2017-11-30 22:50
@ukdtom ?

**Comment by creoludifico** [comment] 2017-11-30 22:53
The optimal solution here would be a backend filtering btw.

**Comment by OttoKerner** [comment] 2017-11-30 23:02
Do they get fetched out-of-order? That'd be sub-optimal, to say the least.

**Comment by trumpy81** [comment] 2017-12-01 00:09
It seems to be working for me now (latest translation build, Load More does not display any additional files without subtitles at least, but the 'hide movies without subtitles' option is not being applied to TV Series.

**Comment by ukdtom** [comment] 2017-12-02 10:53
@creoludifico 

I see you call backend like:

`http://qnap2:33400/api/v3/pms/getSection/key/25/start/0/size/20/getSubs/title/`

The /title is only valid with a title to search from, and you are not entering any.....
Please drop the `/title`

Regarding doing this in the backend, then I sadly agree, but can't, since you are not storing the prefs about hiding or not ;)
If you could do that, I'll make the change in the backend

@OttoKerner No sort is done....It's handed over just as PMS get's it, which is sorted by title, from the backend

@trumpy81 Confirmed, and if @creoludifico sets the prefs, I'll make sure it's handled in the backend

**Comment by ukdtom** [comment] 2017-12-02 11:04
@creoludifico 

Go with a setting named `/api/v3/settings/getSettings/HideWithoutSubs`

Set to a string value of "True" or "False"

**Comment by ukdtom** [comment] 2017-12-02 11:39
Backend fixed with above commit

**Comment by creoludifico** [comment] 2017-12-03 14:31
Fixed. 

@ukdtom i've made some change in the backend. Feel free to merge with me

**Comment by ukdtom** [comment] 2017-12-03 15:35
And working nicely

**Closed by ukdtom** 2017-12-03 15:35 UTC
Labels: BLOCKER, Gui V3, Module: Subs, Ready for testing
