### ISSUE TITLE
[All] Add search function to SUB module

### ISSUE THREAD

**Issue by dagalufh** [ukdtom/WebTools.bundle#171] opened 2016-04-27 17:49 UTC
Add a function that allows the frontend to search for a movie or a tv show.
Episodes are not really needed so just show name and movie title.

Prefered returnvalue would be the key of the item/items in question and let the frontend query for the rest of the information. That would make it a generic function that can be placed in pm module or something alike.

**Comment by ukdtom** [comment] 2016-04-27 19:59
SNIFF....PAyback time I guess :-)

**Comment by ukdtom** [comment] 2016-04-30 15:44
Duplicate of https://github.com/dagalufh/WebTools.bundle/issues/162
So guess you really want this :-P

Closing the other one

**Comment by ukdtom** [comment] 2016-04-30 19:38
Fixed in https://github.com/dagalufh/WebTools.bundle/commit/f89ca317d240288b52f5e1fc979826905118b739

**Comment by ukdtom** [comment] 2016-04-30 19:55
Now up to you :-)

**Comment by creoludifico** [comment] 2017-01-21 22:33
If it's findmedia module i need the following issue to be resolved first
https://github.com/ukdtom/WebTools.bundle/issues/227

**Comment by ukdtom** [comment] 2017-01-21 22:52
And when said, this is not related to FM, AFAIK

It's related to the SubTitle module, where one can search for a movie or show, in order to fix subs

**Comment by creoludifico** [comment] 2017-01-21 22:54
Roger that

**Comment by creoludifico** [comment] 2017-02-02 17:47
Search imp but only for movies for now.
I need some rework on the search func in backend for v3

**Comment by ukdtom** [comment] 2017-02-12 16:59
Perfect

**Closed by ukdtom** 2017-02-12 16:59 UTC
Labels: enhancement, Ready for testing
