### ISSUE TITLE
Copy user to myself

### ISSUE THREAD

**Issue by janotlessard** [ukdtom/WebTools.bundle#536] opened 2019-02-22 16:10 UTC
First of all, Excuse my english.

With Plex in my family, We are 4 users. I would like to Export Playlist of my daughter to -Self- (my self) but I'm not able. We have no problem to copy playlist between all users, exept -Self- not working.

Thank you very much for your answers.

Janot.

**Comment by ukdtom** [comment] 2019-02-22 19:27
Duplicate of https://github.com/ukdtom/WebTools.bundle/issues/464

**Closed by ukdtom** 2019-02-22 19:27 UTC
